version: "3.8"

services:
  pgdb:
    image: postgres:10
    container_name: lotin_kiril_db
    environment:
      - POSTGRES_DB=lotin_kiril
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: lotin_kiril_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - pgdb
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s


volumes:
    pgdb:
    web:






