version: "3.8"

services:
  db_name:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_DB=lotin_kiril
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
   
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_DB=lotin_kiril
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=123
    depends_on:
      - db_name
    env_file:
      - .env

  telegram_bot:
    build: .
    container_name: telegram_bot
    command: python bot/translate.py
    volumes: 
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    restart: always
    ports: 
      - "5000:5000"
    depends_on: 
      - web

volumes:
    db_name:
    web:




