name: Second Server Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: 92.53.96.41
        USERNAME: uzdevid_abhrbot
        PASSWORD: 7dJQ7sJT
        PORT: 22
        script: |
          cd public_html
          cd admin
          git pull
          
          docker-compose down
          docker-compose build
          docker-compose up
      
      